
import os
import parameters as params

num_proc = 7
pos_list, conductivity, path, sbspt = params.default_run('anisotropic')


def gen_bash_script(pos_list, num_proc):
    # proc_vals = np.linspace(0, len(pos_list), num_proc + 1).astype(int)
    filename = 'parallel_fem.sh'
    if os.path.isfile(filename):
        os.remove(filename)
    f = open(filename, 'w')
    f.write('# generated by generate_parallel.py\n')
    for proc_idx in range(num_proc):
        # pt_idxs = range(proc_vals[proc_idx - 1], proc_vals[proc_idx])
        # fresh_lst = [pos_list[ii] for ii in pt_idxs]
        if proc_idx < num_proc - 1:
            f.write('python forward_pts.py '
                    + str(num_proc) + ' '
                    + str(proc_idx + 1) + ' &\n')
        else:
            f.write('python forward_pts.py '
                    + str(num_proc) + ' '
                    + str(proc_idx + 1) + '\n')
    f.close()


gen_bash_script(pos_list, num_proc)
